# Generated by Django 5.1.4 on 2024-12-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageIcon', models.ImageField(upload_to='subscriptionPackageIcon/')),
                ('packageName', models.CharField(max_length=100)),
                ('packagePrice', models.CharField(max_length=100)),
                ('minimumClient', models.CharField(max_length=100)),
            ],
        ),
    ]
