# Generated by Django 5.1.4 on 2024-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageIcon', models.ImageField(blank=True, null=True, upload_to='subscriptionPackageIcon/')),
                ('packageName', models.CharField(blank=True, max_length=100, null=True)),
                ('packagePrice', models.CharField(blank=True, max_length=100, null=True)),
                ('minimumClient', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
