# Generated by Django 5.1.4 on 2024-12-28 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon/')),
                ('wattermarkIcon', models.ImageField(upload_to='wattermarkIcon/')),
                ('serviceTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('mainTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('navLogo', models.ImageField(upload_to='logo/')),
                ('banner', models.ImageField(upload_to='banner/')),
                ('title', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('buttonText', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField(verbose_name=django.core.validators.MaxLengthValidator(6, 'Zip code must be 6 digits long.'))),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteractivePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='platform/')),
            ],
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_one', models.ImageField(upload_to='partner/')),
            ],
        ),
        migrations.CreateModel(
            name='WhySubscriptionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhySubscriptionShareList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='subscriptionIcon/')),
                ('modelTitle', models.CharField(max_length=100)),
                ('modelDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteractivePlatformList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('interactivePlatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractivePlatformList', to='adminControl.interactiveplatform')),
            ],
        ),
    ]
