# Generated by Django 5.1.4 on 2024-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_one', models.ImageField(blank=True, null=True, upload_to='partner/')),
            ],
        ),
    ]
