# Generated by Django 5.1.4 on 2024-12-27 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='', upload_to='icon/')),
                ('wattermarkIcon', models.ImageField(default='', upload_to='wattermarkIcon/')),
                ('serviceTitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('mainTitle', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteractivePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform/')),
            ],
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_one', models.ImageField(default='', upload_to='partner/')),
            ],
        ),
        migrations.CreateModel(
            name='WhySubscriptionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhySubscriptionShareList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subscriptionIcon/')),
                ('modelTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('modelDescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='general',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='banner',
            field=models.ImageField(default='', upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='buttonText',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='favicon',
            field=models.ImageField(default='', upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='navLogo',
            field=models.ImageField(default='', upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='zipCode',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MaxLengthValidator(6, 'Zip code must be 6 digits long.')),
        ),
        migrations.CreateModel(
            name='InteractivePlatformList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('interactivePlatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractivePlatformList', to='adminControl.interactiveplatform')),
            ],
        ),
    ]
