# Generated by Django 5.1.4 on 2024-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0002_commercialservices_interactiveplatform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveplatform',
            name='image',
            field=models.ImageField(default='', upload_to='platform/'),
        ),
        migrations.AlterField(
            model_name='interactiveplatformlist',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interactiveplatformlist',
            name='icon',
            field=models.ImageField(default='', upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='interactiveplatformlist',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whysubscriptionshare',
            name='subTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whysubscriptionshare',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whysubscriptionsharelist',
            name='icon',
            field=models.ImageField(default='', upload_to='subscriptionIcon/'),
        ),
        migrations.AlterField(
            model_name='whysubscriptionsharelist',
            name='modelDescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whysubscriptionsharelist',
            name='modelTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
