# Generated by Django 5.1.4 on 2024-12-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0003_commercialservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialservices',
            old_name='title',
            new_name='mainTitle',
        ),
        migrations.AddField(
            model_name='commercialservices',
            name='serviceTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
