# Generated by Django 5.1.4 on 2024-12-19 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0005_interactiveplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveplatform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interactiveplatform',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='interactiveplatform',
            name='title',
        ),
        migrations.CreateModel(
            name='InteractivePlatformList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('interactivePlatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminControl.interactiveplatform')),
            ],
        ),
    ]
