# Generated by Django 5.1.4 on 2024-12-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0006_remove_interactiveplatform_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveplatformlist',
            name='interactivePlatform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractivePlatformList', to='adminControl.interactiveplatform'),
        ),
    ]
