# Generated by Django 5.1.4 on 2024-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0007_alter_interactiveplatformlist_interactiveplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriptionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subscriptionIcon/')),
                ('modelTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('modelDescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
