# Generated by Django 5.1.4 on 2024-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0008_subscriptionshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhySubscriptionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhySubscriptionShareList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subscriptionIcon/')),
                ('modelTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('modelDescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='subscriptionShare',
        ),
    ]
