# Generated by Django 5.1.4 on 2024-12-23 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0010_subscriptionpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='contact',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxLengthValidator(15, 'Contact number must be 15 digits long.')),
        ),
        migrations.AlterField(
            model_name='general',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxLengthValidator(6, 'Zip code must be 6 digits long.')),
        ),
    ]
