# Generated by Django 5.1.4 on 2024-12-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0011_alter_general_contact_alter_general_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPackage',
        ),
    ]
