# Generated by Django 5.1.4 on 2024-12-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAuth', '0002_customuser_bou_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bou_name',
        ),
    ]
