# Generated by Django 5.1.4 on 2025-01-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAuth', '0003_remove_customuser_bou_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='adminProfileImage/'),
        ),
    ]
