# Generated by Django 5.1.4 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='buttonText',
            field=models.CharField(default='Contact Us Now', max_length=50),
        ),
    ]
